# Este arquivo é a main config do plugin KCore onde influenciará em seu funcionamento...
# Criador: Gilberto Damim;
# Github: https://github.com/GilbertoDamim/KCore;
# Quaisquer duvidas entrar em contato no discord Gilberto (K_Plugins)#5620 ou mesmo pelo github;
# Este projeto está em desenvolvimento porfavor tenha paciencia do projeto final;
# Escolha o tipo de armazenamento do plugin, disponiveis: h2, mysql;
# futuros tipos de armazenamento: postgresql, sqlserver.
General:
  selected-lang: pt_BR
Database:
  type: h2
  sql-ip: localhost
  sql-port: 3306
  sql-username: u0_kcore
  sql-database: s0_kcore
  sql-password: kcore123
Kits:
  activated: true
  use-short-time: false
  sucess: BLOCK_NOTE_BLOCK_PLING
  problem: BLOCK_NOTE_BLOCK_BASS