name: EssentialsGD
version: 1.1
author: Gilberto
api-version: 1.13
main: me.gilberto.essentials.EssentialsMain
description: Essentials for minecraft
commands:
  kit:
    description: comando kits
  editkit:
    description: comando kits
  createkit:
    description: comando kits
  delkit:
    description: comando kits
  essentials:
    description: comando principal