# This file is the main configuration of the command's will influence its operation...
# Creator: Gilberto Damim;
# Github: https://github.com/GilbertoKPL/EssentialsK;
# Any questions, please contact Gilberto_KPL#5620 or even at GitHub;
# This project is under development please be patient with the final project;
kits:
  # Enabled.
  activated: true
  # Enable short name of time, example seconds to s.
  use-short-time: false
  # Drop items when he gets the kit.
  drop-items-in-catch: false
  # Equip armour when he gets the kit.
  equip-armor-in-catch: true
nicks:
  # Enabled.
  activated: true
  # If enabled players can have same nick.
  can-player-have-same-nick: false
  # List of blocked nicks.
  blocked-nicks:
    - essentialsk
homes:
  # Enabled.
  activated: true
  # Default value if player not have permission
  default-limit-homes: 3
  # Time in seconds to teleport to determined location, has a permission to bypass.
  time-to-teleport: 5
  # List of blocked worlds to use sethome.
  block-worlds:
    - essentialsk
warps:
  # Enabled.
  activated: true
  # Time in seconds to teleport to determined location, has a permission to bypass.
  time-to-teleport: 5
tp:
  # Enabled.
  activated: true
tpa:
  # Enabled.
  activated: true
  # Time in seconds to accept order.
  time-to-accept: 10
  # Time in seconds to teleport to determined location, has a permission to bypass.
  time-to-teleport: 5
echest:
  # Enabled.
  activated: true
gamemode:
  # Enabled.
  activated: true
vanish:
  # Enabled.
  activated: true
  # Blocked cmds from others Players when Player is vanished, <player> is vanished Player and <arg> if other value from cmd.
  blocked-other-cmds:
    - "/tell <player>"
    - "/money <arg> <player>"