general:
  # Selected Lang to run your plugin, it is necessary to have it in your lang folder, You can add more languages by contributing to the plugin....
  selected-lang: pt_BR
  # Nome do seu servidor.
  server-name: unamed
  # auto update
  auto-update: true
database:
  # Selecione a sua conexão, Disponiveis H2 (Local) e Mysql (Nuvem).
  type: H2
  # Se selecionou MYSQL coloque essas informações paar conexão.
  sql-ip: 'localhost'
  sql-port: '3306'
  sql-username: "!u0_essentialsk"
  sql-database: "!s0_essentialsk"
  sql-password: "!essentialsk123"
# Conexão com o Discord.
discordbot:
  # Token do Bot.
  token: "123456"
  # Se estiver ativado (true), O discord conectará com o chat do discord.
  connect-discord-chat: false
  # Caso o connect esteja ativado terá que colocar o id do chat conectado aqui.
  id-discord-chat: "123456"
  # Comando que ira detectar para enviar ao discord.
  command-chat:
    - "/g"
    - "/global"
  # Tamanho máximo da mensagem que o discord conseguirá enviar ao server.
  max-message-lenght: 50
  # Mandar mensagem ao discord (embed) que o ‘player’ logou.
  send-login-message: false
  # Mandar mensagem ao discord (embed) que o ‘player‘ saiu.
  send-leave-message: false
  # Mudar o assunto do canal a cada 10 minutos, com a mensagem setada na sua lang.
  send-topic-update: false
# Config dos comandos Kits.
kits:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Se estiver ativado (true), será enviado um menu ao ‘player’.
  menu-kit: true
  # Se estiver ativado (true), será enviado o tempo em pequena escala, exemplo segundos para s.
  use-short-time: false
  # Se estiver ativado (true) dropar items caso o invetário esteja cheio.
  drop-items-in-catch: false
  # Se estiver ativado (true), será Equipado a armadura caso tenha no kit.
  equip-armor-in-catch: true
# Config dos comandos Nicks.
nicks:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Se estiver ativado (true) players poderão usar o mesmo nick.
  can-player-have-same-nick: false
  # Lista de nicks bloqueados.
  blocked-nicks:
    - essentialsk
# Config dos comandos Homes.
homes:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Quantidade de homes maximas caso não tenha a permissão.
  default-limit-homes: 3
  # Tempo para teleportar, tem permissão para burlar isso.
  time-to-teleport: 5
  # Lista de mundos bloqueados de usar sethome, use o nome do mundo exemplo: world.
  block-worlds:
    - essentialsk
# Config dos comandos Warps.
warps:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Tempo para teleportar, tem permissão para burlar isso.
  time-to-teleport: 5
# Config dos comandos TP.
tp:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos TPhere.
tphere:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos TPA.
tpa:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Tempo para aceitar o pedido.
  time-to-accept: 10
  # Tempo para teleportar, tem permissão para burlar isso.
  time-to-teleport: 5
# Config dos comandos Lixo.
trash:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos Craft.
craft:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos Speed.
speed:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos Echest.
echest:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos Gamemode.
gamemode:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos Vanish.
vanish:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Comandos Bloqueados se um outro player executar em nome da pessoa de vanish bloquear.
  blocked-other-cmds:
    - "/tell <player>"
    - "/money <arg> <player>"
# Config dos comandos Feed.
feed:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Só vai executar se sua fome não estiver cheia, em versões antias pode bugar no true.
  need-eat-below: false
# Config dos comandos Heal.
heal:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Só vai executar se sua vida não estiver cheia, em versões antias pode bugar no true.
  need-heal-below: false
# Config dos comandos Light.
light:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config dos comandos Back.
back:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Lista de mundos bloqueados de salvarem no back, use o nome do mundo exemplo: world.
  disabled-worlds:
    - essentialk
# Config dos comandos Spawn.
spawn:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Se estiver ativado o player será mandado para o spawn no login.
  send-to-spawn-on-login: true
  # Se estiver ativado o player será mandado para o spawn quando ele morre.
  send-to-spawn-on-death: true
  # Tempo para teleportar, tem permissão para burlar isso.
  time-to-teleport: 5
# Config dos comandos Fly.
fly:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Lista de mundos bloqueados de usar o fly, use o nome do mundo exemplo: world.
  disabled-worlds:
    - essentialk
# Config dos comandos Online.
online:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Se estiver ativado (true), O comando online contará também os players de vanish.
  count-remove-vanish: false
# Config dos comandos anunciar.
hat:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
announce:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
  # Tempo em segundos para executar o comando novamente.
  cooldown: 300
invsee:
  # Se estiver ativado (true), O comando será ativado.
  activated: true
# Config da MOTD.
motd:
  # Se estiver ativado (true), O Motd será ativado.
  enabled: true
  # Adicionar lista para ver no motd use (/ n> 1.5.2) para pular linhas;
  # Lista de motds aletórias, caso queira estático utilize só 1 linha;
  # Variaveis -> %players_online%.
  list-motd:
    - '&1Minecraft Server \n&1Está aberto com players %players_online% online!'
    - '&2Minecraft Server \n&2Está aberto com players %players_online% online!'
    - '&3Minecraft Server \n&3Está aberto com players %players_online% online!'
    - '&4Minecraft Server \n&4Está aberto com players %players_online% online!'
# Config das mensagens automáticas.
announcements:
  # Se estiver ativado (true), as mensagens automáticas serão ativadas.
  enabled: true
  # Tempo entre as mensagens em minutos para enviar.
  time: 5
  # Lista de anuncios para ser enviado;
  # Variaveis -> %players_online%.
  list-announce:
    - '&eSeu servidor está utilizando EssentiasK, obrigado por utilizar.'
    - '&9Obrigado por utilizar meu plugin!'
    - '&3No servidor tem %players_online% players online!'
# Neste local, existem as mensagens que podem ser ativadas.
messages:
  # Se estiver ativado (true), as mensagens do login será ativada.
  login-message: true
  # Se estiver ativado (true), as mensagens do leave será ativada.
  leave-message: true
  # Se estiver ativado (true), as mensagens do deathmessages serão ativadas.
  deathmessages-message: true
# Neste local, contém os recursos antibugs que podem ser ativados ou desativados.
antibugs:
  # Neste recurso, o jogador é impedido de subir na cama;
  # Permissão Bypass -> essentialsk.bypass.bed.
  block-bed: true
  # Neste recurso, o jogador é impedido de subir nos veículos;
  # Permissão Bypass -> essentialsk.bypass.vehicles.
  block-climbing-on-vehicles: true
  # Neste recurso, o jogador é impedido de usar NameTag em mobs;
  # Permissão Bypass -> essentialsk.bypass.nametag.
  block-nametag: false
  # Neste recurso, os mobs são proibidos de pegar itens do chão.
  block-mob-catch: false
  # Neste recurso, bloqueia o jogador de ir além da borda com Ender Pearls.
  block-going-edge-enderpearl: true
  # Neste recurso, bloqueia o jogador de ir para o teto do Nether;
  # Permissão Bypass -> essentialsk.bypass.netherceiling.
  block-player-go-to-nether-ceiling: true
  # Neste recurso, os blocos de jogadores se teletransportam em portais;
  # Permissão Bypass -> essentialsk.bypass.teleportportal.
  block-player-teleport-portal: true
  # Neste recurso, bloqueia todas as entidades criar portais.
  block-create-portal: false
  # Neste recurso, bloquear os player de utilizarem esses comandos;
  # Permissão Bypass -> essentialsk.bypass.blockedcmd.
  block-cmds:
    - "/pl"
    - "/plugins"
# Neste local, contém as opções do container, lista de valores em (indisponível por enquanto).
containers:
  # Cancelar o uso de shift nos contêineres da lista;
  # Permissão Bypass -> essentialsk.bypass.shiftcontainer.
  block-shift-enable: false
  # List to block shift;
  # Lista para bloquear shift.
  block-shift:
    - 'ANVIL'
  # Cancelar abrir os contêineres da lista;
  # Permissão Bypass -> essentialsk.bypass.opencontainer.
  block-open-enable: false
  # Lista para bloquear de abrir.
  block-open:
    - 'ANVIL'
# Neste local, possui addons para minecraft.
addons:
  # Neste recurso, a bigorna é infinita.
  infinity-anvil: true
  # Neste recurso, o jogador é teletransportado para o spawn se o jogador cair no void.
  block-player-go-to-void: true
  # Neste recurso, os itens dropados não podem explodir.
  block-explode-items: true
  # Neste recurso, o jogador não pode quebrar a plantação quando cair.
  block-player-break-plantation-fall: true
  # Neste recurso, o fogo não pode se propagar.
  block-propagation-fire: true
  # Neste recurso, pode ser colocado & no nome do ‘item’, tem permissão para isso;
  # Permissão -> essentialsk.color.&0 (Exemplo).
  color-in-anvil: true
  # Neste recurso, pode ser colocado & no sinal, tem uma permissão para isso;
  # Permissão -> essentialsk.color.&0 (Exemplo).
  color-in-sign: true
  # Neste recurso, pode ser colocado & no bate-papo, tem permissão para isso.
  # Permissão -> essentialsk.color.&0 (Exemplo).
  color-in-chat: true
  # Neste recurso, evita que o jogador perca XP na morte.
  player-prevent-lose-xp: true
  # Neste recurso, evita que começe a chover.
  disable-rain: true