general:
  # Selected Lang to run your plugin, it is necessary to have it in your lang folder, You can add more languages by contributing to the plugin....
  selected-lang: en_US
  # this line its necessary to log errors.
  server-name: unamed
database:
  # Select Database type, available: H2 or MYSQL.
  type: H2
  # If you have selected MYSQL add ip, port, username, database and password.
  sql-ip: 'localhost'
  sql-port: '3306'
  sql-username: 'u0_essentialsk'
  sql-database: 's0_essentialsk'
  sql-password: 'essentialsk123'