# This file is the main configuration of the EssentialsK plugin where it will influence its operation...
# Creator: Gilberto Damim;
# Github: https://github.com/GilbertoKPL/EssentialsK;
# Any questions, please contact Gilberto_KPL#5620 or even at GitHub;
# This project is under development please be patient with the final project;
general:
  #Selected Lang to run your plugin, it is necessary to have it in your lang folder, You can add more languages by contributing to the plugin....
  selected-lang: en_US
database:
  #Select Database type, available: H2 or MYSQL.
  type: H2
  #If you have selected MYSQL add ip, port, username, database and password.
  sql-ip: localhost
  sql-port: 3306
  sql-username: u0_essentialsk
  sql-database: s0_essentialsk
  sql-password: essentialsk123
kits:
  #Enabled ?
  activated: true
  #Enable short name od time example, seconds to s.
  use-short-time: false
  #drop items when he gets the kit ?
  drop-items-in-catch: false
  #equip armour when he gets the kit ?
  equip-armor-in-catch: true
nicks:
  activated: true
  can-player-have-same-nick: false
  blocked-nicks:
    - essentialsk