motd:
  # Enabled
  enabled: true
  # Add List to see in motd use (/n > 1.5.2) to skip lines.
  # Variables -> %players_online%.
  list-motd:
    - '&1Minecraft Server \n&1its open with %players_online% online!'
    - '&2Minecraft Server \n&2its open with %players_online% online!'
    - '&3Minecraft Server \n&3its open with %players_online% online!'
    - '&4Minecraft Server \n&4its open with %players_online% online!'

announcements:
  # Enabled
  enabled: true
  # Time to send in minutes
  time: 5
  # Add List to send.
  # Variables -> %players_online%.
  list-announce:
    - '&1Your server has using EssentialsK plugin!'
    - '&2Thanks for using me the plugin!'